---
# Setup Configuration Files

- name: Bash Profile Configuration
  ansible.builtin.template:
    src: files/bash_profile.j2
    dest: /home/{{ ansible_user }}/bash_profile
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Bash Aliases Configuration
  ansible.builtin.template:
    src: files/bash_aliases.j2
    dest: /home/{{ ansible_user }}/bash_aliases
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Bashrc Configuration
  ansible.builtin.template:
    src: files/bashrc.j2
    dest: /home/{{ ansible_user }}/.bashrc
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Alacritty Configuration
  ansible.builtin.template:
    src: files/alacritty.yml.j2
    dest: /home/{{ ansible_user }}/.config/alacritty/alacritty.yml
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"

- name: Fail2Ban Configuration
  ansible.builtin.template:
    src: files/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"

- name: SSH Configuration
  ansible.builtin.template:
    src: files/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"

- name: Tmux Configuration
  ansible.builtin.template:
    src: files/tmux.conf.j2
    dest: /home/{{ ansible_user }}/.tmux.conf
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0644"
