---
# Setup Configuration Files

- name: Bash Profile Configuration
  ansible.builtin.copy:
    src: files/bash_profile
    dest: /home/{{ ansible_user_id }}/.bash_profile
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Bash Aliases Configuration
  ansible.builtin.copy:
    src: files/bash_aliases
    dest: /home/{{ ansible_user_id }}/bash_aliases
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Bashrc Configuration
  ansible.builtin.copy:
    src: files/bashrc
    dest: /home/{{ ansible_user_id }}/.bashrc
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Create Alacritty Directory
  ansible.builtin.file:
    path: /home/{{ ansible_user_id }}/.config/alacritty
    state: directory
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0755"

- name: Alacritty Configuration
  ansible.builtin.copy:
    src: files/alacritty.yml
    dest: /home/{{ ansible_user_id }}/.config/alacritty/alacritty.yml
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: Fail2Ban Configuration
  become: true
  ansible.builtin.template:
    src: files/jail.local.j2
    dest: /etc/fail2ban/jail.local
    owner: root
    group: root
    mode: "0644"

- name: SSH Configuration
  become: true
  ansible.builtin.template:
    src: files/sshd_config.j2
    dest: /etc/ssh/sshd_config
    owner: root
    group: root
    mode: "0644"
  register: sshd_config

- name: Restart SSH Service
  become: true
  ansible.builtin.service:
    name: sshd
    state: restarted
  notify: Restart SSH

- name: Tmux Configuration
  ansible.builtin.template:
    src: files/tmux.j2
    dest: /home/{{ ansible_user_id }}/.tmux.conf
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"
