---

- name: Check if Gnome Shell extension is already installed - {{ gnome_extension_info.name }}
  ansible.builtin.stat:
    path: "/home/{{ local_user }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}/metadata.json"
  register: r_gnome_extensions_check_existing

- name: Create temporary download directory
  ansible.builtin.tempfile:
    state: directory
    suffix: ".gnome_extension_download"
  register: r_gnome_extension_download_dir
  changed_when: false
  when: not r_gnome_extensions_check_existing.stat.exists

- name: Download and Install Gnome Shell extension - {{ gnome_extension_info.name }} # noqa: partial-become no-changed-when key-order
  block:
    - name: Download Gnome Shell extension - {{ gnome_extension_info.name }} # noqa: risky-file-permissions
      ansible.builtin.get_url:
        url: https://extensions.gnome.org{{ gnome_extension_info.download_url }}
        dest: "{{ r_gnome_extension_download_dir.path }}/{{ gnome_extension_info.uuid }}.zip"
      register: r_gnome_extension_download

    - name: Create install directory - {{ gnome_extension_info.name }}
      ansible.builtin.file:
        path: "/home/{{ local_user }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
        state: directory
        owner: "{{ local_user }}"
        group: "{{ local_user }}"
        mode: "0755"

    - name: Install Gnome Shell extension - {{ gnome_extension_info.name }}
      ansible.builtin.unarchive:
        src: "{{ r_gnome_extension_download.dest }}"
        dest: "/home/{{ local_user }}/.local/share/gnome-shell/extensions/{{ gnome_extension_info.uuid }}"
        remote_src: true

    - name: Enable Gnome Shell extension - {{ gnome_extension_info.name }} # noqa: partial-become no-changed-when
      ansible.builtin.command: gnome-shell-extension-tool --enable-extension {{ gnome_extension_info.uuid }}
  always:
    - name: Delete temporary download directory
      ansible.builtin.file:
        path: "{{ r_gnome_extension_download_dir.path }}"
        state: absent
      changed_when: false
  when: not r_gnome_extensions_check_existing.stat.exists
