---
- name: Setup Gnome
  community.general.dconf:
    key: "{{ item.k }}"
    value: "{{ item.v }}"
    state: present
  become: true
  become_user: "{{ local_user }}"
  when: not is_container | default(false)
  loop:
    - k: /org/gnome/desktop/interface/clock-format
      v: "'12h'"

    - k: /org/gnome/desktop/boxes/first-run
      v: "false"

    - k: /org/gnome/desktop/interface/cursor-theme
      v: "'Adwaita'"

    - k: /org/gnome/desktop/interface/enable-hot-corners
      v: "false"

    - k: /org/gnome/desktop/interface/gtk-theme
      v: "'Adwaita-dark'"

    - k: /org/gnome/desktop/interface/color-scheme
      v: "'prefer-dark'"

    - k: /org/gnome/desktop/interface/icon-theme
      v: "'Adwaita'"

    - k: /org/gnome/desktop/interface/show-battery-percentage
      v: "true"

    - k: /org/gnome/desktop/datetime/automatic-timezone
      v: "true"

    - k: /org/gnome/desktop/privacy/remember-app-usage
      v: "false"

    - k: /org/gnome/system/location/enabled
      v: "true"

    - k: /org/gnome/system/location/max-accuracy-level
      v: "'exact'"

    - k: /org/gnome/terminal/legacy/confirm-close
      v: "false"

    - k: /org/gnome/terminal/legacy/shell-integration-enabled
      v: "true"

    - k: /org/gnome/terminal/legacy/theme-variant
      v: "'dark'"

    - k: /org/gnome/terminal/legacy/unified-menu
      v: "false"

    - k: /org/gnome/shell/overrides/dynamic-workspaces
      v: "false"

    - k: /org/gnome/mutter/dynamic-workspaces
      v: "false"

    - k: /org/gnome/desktop/wm/preferences/num-workspaces
      v: 5

    - k: /org/gnome/shell/overrides/workspaces-only-on-primary
      v: "true"

    - k: /org/gnome/shell/window-switcher/current-workspace-only
      v: "false"

    - k: /org/gnome/desktop/peripherals/touchpad/natural-scroll
      v: "false"

    - k: /org/gnome/desktop/peripherals/touchpad/tap-to-click
      v: "false"

    - k: /org/gnome/desktop/peripherals/touchpad/click-method
      v: "'fingers'"

    - k: /org/gnome/desktop/wm/keybindings/switch-applications
      v: "['<Alt>Tab']"

    - k: /org/gnome/desktop/wm/keybindings/switch-applications-backward
      v: "['<Shift><Alt>Tab']"

    - k: /org/gnome/desktop/wm/keybindings/switch-windows
      v: "@as []"

    - k: /org/gnome/desktop/wm/keybindings/switch-windows-backward
      v: "@as []"

    - k: /org/gnome/peripherals/mouse/natural-scroll
      v: "false"

    - k: /org/gnome/desktop/wm/preferences/button-layout
      v: "'appmenu:minimize,maximize,close'"

    - k: /org/gnome/shell/weather/automatic-location
      v: "true"

    - k: /org/gnome/shell/weather/locations
      v: "[<(uint32 2, <('Indianapolis', 'KIND', true, [(0.69333204535474746, -1.5059040078213661)], [(0.69408911682438501, -1.5037415099715601)])>)>]"

    - k: /org/gnome/clocks/world-clocks
      v: "[{'location': <(uint32 2, <('New York', 'KNYC', true, [(0.71174266133038869, -1.2909618760458005)], [(0.71174266133038869, -1.2909618760458005)])>)>},
        {'location': <(uint32 2, <('Chicago', 'KORD', true, [(0.73087131210925766, -1.5294370491003432)], [(0.73087131210925766, -1.5294370491003432)])>)>},
        {'location': <(uint32 2, <('Denver', 'KDEN', true, [(0.69356499048035111, -1.8325180844752899)], [(0.69356499048035111, -1.8325180844752899)])>)>},
        {'location': <(uint32 2, <('Los Angeles', 'KLAX', true, [(0.59441327990644397, -2.0636403894159987)], [(0.59441327990644397, -2.0636403894159987)])>)>}]"

- name: Disable Ubuntu Dock and Desktop Icons NG (ding) extensions
  ansible.builtin.command: "gnome-extensions disable {{ item }}"
  become: true
  become_user: "{{ local_user }}"
  when: not is_container | default(false)
  changed_when: false
  failed_when: false
  loop:
    - ubuntu-dock@ubuntu.com
    - ding@rastersoft.com

- name: Install and enable GNOME Shell extensions
  ansible.builtin.import_tasks: extensions.yml
  when: not is_container | default(false)
