---
dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ubuntu:24.04
    privileged: true
    command: /bin/bash -c "while true; do sleep 30; done"
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/roles"
  playbooks:
    converge: converge.yml
verifier:
  name: ansible
