---
# Install commom Ubuntu Packages
- name: Install Common System Packages
  become: true
  ansible.builtin.package:
    name:
      - automake
      - awscli
      - bat
      - build-essential
      - cargo
      - cmake
      - direnv
      - docker-compose
      - docker.io
      - exa
      - fail2ban
      - ffmpeg
      - htop
      - iotop
      - jq
      - letsencrypt
      - libfontconfig-dev
      - lshw
      - lsscsi
      - mlocate
      - neovim
      - ngrep
      - nmon
      - nmap
      - npm
      - pkg-config
      - python3-psutil
      - python3-termcolor
      - ripgrep
      - speedtest-cli
      - ssh
      - sysstat
      - tmux
      - unzip
      - vagrant
      - vagrant-libvirt
      - virtualbox
      - vlc
    state: present