---
# Add apt repositories
- name: Apt Key for Google Chrome
  become: true
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Google Chrome Stable Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    validate_certs: false
    state: present
    update_cache: true

- name: Apt Key for Docker
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    validate_certs: false
    state: present
    update_cache: true

- name: Apt Key for HashiCorp
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: HashiCorp Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    validate_certs: false
    state: present
    update_cache: true

- name: 1password Apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: 1password Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main
    validate_certs: false
    state: present
    update_cache: true

- name: Apt Key for Boundary
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Boundary Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    validate_certs: false
    state: present
    update_cache: true

- name: VSCode Apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: VSCode Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/code stable main
    validate_certs: false
    state: present
    update_cache: true

# Install commom Ubuntu Packages
- name: Install Packages
  become: true
  ansible.builtin.package:
    name:
      - automake
      - awscli
      - bat
      - boundary
      - cmake
      - code
      - consul
      - dconf-editor
      - direnv
      - docker.io
      - docker-compose
      - exa
      - fail2ban
      - ffmpeg
      - gnome-extensions-app
      - gnome-photos
      - gnome-calendar
      - gnome-contacts
      - gnome-tweaks
      - google-chrome-stable
      - htop
      - iotop
      - jq
      - letsencrypt
      - lshw
      - lsscsi
      - mlocate
      - neovim
      - ngrep
      - nomad
      - nmon
      - nmap
      - npm
      - owncloud-client
      - packer
      - python3-psutil
      - python3-termcolor
      - remmina
      - ripgrep
      - slack
      - snapd
      - speedtest-cli
      - ssh
      - sysstat
      - terraform
      - tmux
      - totem
      - transmission
      - unzip
      - vagrant
      - vagrant-libvirt
      - vault
      - virtualbox
      - vlc
      - waypoint
    state: present

- name: Install Snap Packages
  become: true
  community.general.snap:
    name:
      - alacritty
      - discord
      - vlc
      - zoom-client
    classic: true
    dangerous: true
    state: present

# Remove unneeded packages
- name: Remove Packages
  become: true
  ansible.builtin.package:
    name:
      - firefox
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      - gnome-tetravex
      - gnome-weather
      - rhythmbox
      - shotwell
      - simple-scan
      - thunderbird
      - ubuntu-web-launchers
      - yelp
    state: absent
