
---
# Add apt repositories
- name: Apt Key for Google Chrome
  become: true
  ansible.builtin.apt_key:
    url: https://dl.google.com/linux/linux_signing_key.pub
    state: present

- name: Google Chrome Stable Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main
    validate_certs: false
    state: present
    update_cache: true

- name: Apt Key for Docker
  become: true
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Docker Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
    validate_certs: false
    state: present
    update_cache: true

- name: Apt Key for HashiCorp
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: HashiCorp Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    validate_certs: false
    state: present
    update_cache: true

- name: 1password Apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://downloads.1password.com/linux/keys/1password.asc
    state: present

- name: 1password Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://downloads.1password.com/linux/debian/amd64 stable main
    validate_certs: false
    state: present
    update_cache: true

- name: Apt Key for Boundary
  become: true
  ansible.builtin.apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Boundary Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] https://apt.releases.hashicorp.com focal main
    validate_certs: false
    state: present
    update_cache: true

- name: VSCode Apt Key
  become: true
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: VSCode Repo
  become: true
  ansible.builtin.apt_repository:
    repo: deb [arch=amd64] http://packages.microsoft.com/repos/code stable main
    validate_certs: false
    state: present
    update_cache: true

# Install commom Ubuntu Packages
- name: Install Common System Packages
  become: true
  ansible.builtin.package:
    name:
      - automake
      - awscli
      - bat
      - boundary
      - build-essential
      - cargo
      - cmake
      - code
      - consul
      - dconf-editor
      - direnv
      - docker.io
      - docker-compose
      - exa
      - fail2ban
      - ffmpeg
      - gnome-extensions-app
      - gnome-photos
      - gnome-calendar
      - gnome-contacts
      - gnome-tweaks
      - google-chrome-stable
      - htop
      - iotop
      - jq
      - letsencrypt
      - libfontconfig-dev
      - lshw
      - lsscsi
      - mlocate
      - neovim
      - ngrep
      - nomad
      - nmon
      - nmap
      - npm
      - owncloud-client
      - packer
      - pkg-config
      - python3-psutil
      - python3-termcolor
      - remmina
      - ripgrep
      - slack
      - speedtest-cli
      - ssh
      - sysstat
      - terraform
      - tmux
      - totem
      - transmission
      - unzip
      - vagrant
      - vagrant-libvirt
      - vault
      - virtualbox
      - vlc
      - waypoint
    state: present

# Install Zoom deb package
- name: Fetch Zoom
  become: true
  ansible.builtin.get_url:
    url: https://zoom.us/client/latest/zoom_amd64.deb
    dest: /tmp/zoom_amd64.deb
    mode: '0644'

- name: Install Zoom Deb Packages
  become: true
  ansible.builtin.apt:
    deb: /tmp/zoom_amd64.deb
    state: present

- name: Check if Alacritty is installed
  ansible.builtin.stat:
    path: /usr/local/bin/alacritty
  register: alacritty_check

- name: Install Alacritty
  ansible.builtin.command:
    cmd: cargo install alacritty
    creates: /home/{{ ansible_user_id }}/.cargo/bin/alacritty
  when: alacritty_check.stat.exists is not defined or not alacritty_check.stat.exists
  register: alacritty_install

- name: Move Alacritty to /usr/local/bin
  become: true
  ansible.builtin.command:
    cmd: mv /home/{{ ansible_user_id }}/.cargo/bin/alacritty /usr/local/bin/alacritty
    creates: /usr/local/bin/alacritty
  when: alacritty_check.stat.exists is not defined or not alacritty_check.stat.exists

- name: Cleanup Alacritty
  become: true
  ansible.builtin.command:
    cmd: rm -rf /home/{{ ansible_user_id }}/.cargo/bin/alacritty
  when: alacritty_check.stat.exists is not defined or not alacritty_check.stat.exists
  changed_when: alacritty_check.stat.exists is defined and alacritty_check.stat.exists

# Remove unneeded packages
- name: Remove Packages
  become: true
  ansible.builtin.package:
    name:
      - firefox
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      - gnome-tetravex
      - gnome-weather
      - rhythmbox
      - shotwell
      - simple-scan
      - snapd
      - thunderbird
      - ubuntu-web-launchers
      - yelp
    state: absent