---
- name: Create alacritty config directory
  ansible.builtin.file:
    path: /home/{{ local_user }}/.config/alacritty
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0755"
  become: true

- name: Template alacritty.toml
  ansible.builtin.copy:
    src: templates/alacritty.toml
    dest: /home/{{ local_user }}/.config/alacritty/alacritty.toml
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0644"
  become: true
