---
- name: Remove conflicting Alacritty snap
  ansible.builtin.include_tasks:
    file: remove-snap.yml
    apply:
      tags: [third_party, alacritty]
  vars:
    snap_names: [alacritty]
  tags: [third_party, alacritty]

- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/{{ local_user }}/.config/alacritty
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0755"

- name: Template alacritty.toml
  ansible.builtin.template:
    src: templates/alacritty.toml
    dest: /home/{{ local_user }}/.config/alacritty/alacritty.toml
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0644"

- name: Stat alacritty.desktop
  ansible.builtin.stat:
    path: /home/{{ local_user }}/.local/share/applications/alacritty.desktop
  register: alacritty_desktop

- name: Ensure user applications directory exists
  ansible.builtin.file:
    path: /home/{{ local_user }}/.local/share/applications
    state: directory
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0755"
  become: true

- name: Template alacritty.desktop
  ansible.builtin.template:
    src: templates/gnome_desktop/alacritty.desktop
    dest: /home/{{ local_user }}/.local/share/applications/alacritty.desktop
    owner: "{{ local_user }}"
    group: "{{ local_user }}"
    mode: "0644"
  when: not alacritty_desktop.stat.exists

- name: Stat Alacritty Desktop Icon
  ansible.builtin.stat:
    path: /usr/share/applications/Alacritty.desktop
  register: alacritty_stat

- name: Disable Alacritty Built-in icon
  become: true
  ansible.builtin.command: mv /usr/share/applications/Alacritty.desktop /usr/share/applications/Alacritty.desktop.not
  when: alacritty_stat.stat.exists

- name: Stat Gnome Terminal Desktop Icon
  ansible.builtin.stat:
    path: /usr/share/applications/org.gnome.Terminal.desktop
  register: gnome_terminal_stat

- name: Disable Gnome-Terminal Built-in icon
  become: true
  ansible.builtin.command: mv /usr/share/applications/org.gnome.Terminal.desktop /usr/share/applications/org.gnome.Terminal.desktop.not
  when: gnome_terminal_stat.stat.exists

- name: Setup cron to remove Alacritty.desktop every 30 minutes
  become: true
  ansible.builtin.cron:
    name: "Remove Alacritty.desktop"
    minute: "*/30"
    job: "rm -f /usr/share/applications/Alacritty.desktop"
    user: root
    state: present
