---
- name: Check for Chef Workstation
  ansible.builtin.stat:
    path: /opt/chef-workstation/bin/chef
  register: chef_installed
  tags: [third_party, chef]

- name: Install Chef Workstation
  ansible.builtin.apt:
    deb: https://packages.chef.io/files/stable/chef-workstation/22.1.745/ubuntu/22.04/chef-workstation_22.1.745-1_amd64.deb
    state: present
  retries: 3
  when: not chef_installed.stat.exists
  become: true
  tags: [third_party, chef]
