---
- name: Remove legacy Docker packages
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker-ce
      - docker-ce-cli
      - containerd
      - runc
    state: absent
  become: true
  failed_when: false
  tags: [third_party, docker]

- name: Install Docker packages
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-compose
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags: [third_party, docker]

- name: Ensure docker group exists
  ansible.builtin.group:
    name: docker
    state: present
  become: true
  tags: [third_party, docker]

- name: Add user to docker group
  ansible.builtin.user:
    name: "{{ local_user }}"
    groups: [docker]
    append: true
  become: true
  tags: [third_party, docker]
