---
- name: Check for Wine
  ansible.builtin.stat:
    path: /usr/bin/wine
  register: wine_installed
  tags: [third_party, lutris]

- name: Check for Lutris
  ansible.builtin.stat:
    path: /usr/bin/lutris
  register: lutris_installed
  tags: [third_party, lutris]

- name: Add Lutris PPA
  ansible.builtin.apt_repository:
    repo: ppa:lutris-team/lutris
    state: present
    update_cache: true
  become: true
  when: not lutris_installed.stat.exists
  tags: [third_party, lutris]

- name: Install Wine
  ansible.builtin.apt:
    name: wine
    state: present
  when: not wine_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install Lutris
  ansible.builtin.apt:
    name: lutris
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install Vulkan Loader
  ansible.builtin.apt:
    name:
      - libvulkan1
      - mesa-vulkan-drivers
      - vulkan-tools
    state: present
  when: not lutris_installed.stat.exists
  become: true
  tags: [third_party, lutris]

- name: Install missing 32-bit libraries for Lutris
  ansible.builtin.apt:
    name:
      - libfreetype6
      - libgnutls30
      - libldap-2.5-0
      - libgpg-error0
    state: present
  when: not lutris_installed.stat.exists
  become: true
  failed_when: false
  tags: [third_party, lutris]
