---
- name: Apt key for Spotify
  ansible.builtin.apt_key:
    url: https://download.spotify.com/debian/pubkey_6224F9941A8AA6D1.gpg
    state: present
  become: true

- name: Spotify repo
  ansible.builtin.apt_repository:
    repo: deb http://repository.spotify.com stable non-free
    state: present
    update_cache: true
  become: true

- name: Install Spotify client
  ansible.builtin.apt:
    name: spotify-client
    state: present
    update_cache: true
  become: true
