---
- name: Check for VSCode repo
  ansible.builtin.stat:
    path: /etc/apt/sources.list.d/vscode.list
  register: ubuntu_vscode_installed
  tags: [third_party, vscode]

- name: Apt key for Microsoft (VSCode)
  ansible.builtin.apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present
  become: true
  tags: [third_party, vscode]

- name: Add VSCode repo
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
    state: present
    filename: vscode
    update_cache: true
    cache_valid_time: 3600
  when: not ubuntu_vscode_installed.stat.exists
  become: true
  tags: [third_party, vscode]

- name: Install VSCode
  ansible.builtin.apt:
    name: code
    state: present
    update_cache: true
    cache_valid_time: 3600
  become: true
  tags: [third_party, vscode]
