# .github/workflows/ansible-lint.yml
name: ansible-lint
on: [push, pull_request]
jobs:
  ansible-lint:
    name: runner / ansible-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: "3.6"
      - name: ansible-lint
        uses: reviewdog/action-ansiblelint@v1
        with:
          # github_token: ${{ secrets.github_token }}
          # reporter: github-pr-review # Change reporter.
          ansiblelint_flags: '--exclude=./roles/common/files/* --exclude=./roles/common/templates/* --exclude=./roles/configuration/files/* --exclude=./roles/configuration/templates/* --exclude=./roles/gnome/files/* --exclude=./roles/gnome/templates/*'
